import { LinkedList } from './linked-list'

const list = new LinkedList()

list.addToLast(2)
list.addToLast(3)
list.addToLast(4)
list.addToLast(5)
list.addToHead(1)
list.addToHead(9)
list.addElementAtPosition(6, 4)
list.removeFromLast()
list.removeFromHead()
list.removeFirstElementFoundFromList(6)
list.addToLast(3)
list.addToLast(5)
list.addToLast(3)
list.removeAllElementsFromList(3)
console.log(list.search(4))
list.print()
list.reverse()
list.print()
console.log(list.toArray())
list.fromArray([4, 7, 2, 7, 9])
list.print()

// list.removeAlistElementsFromList(3)
// list.addElementAtPosition(6,0)
// list.reverse()
// list.search(11)
// list.search(1)
// list.search(3)
// list.search(5)

// list.print()
